all:
  children:
  # k8s vm
    k8s_servers:
      hosts:
        todo-vm:
          ansible_host: 192.168.122.89
          ansible_user: abdu
          k8s_dir: /media/abdu/11ae6c27-f5e1-4b37-b7f7-733fa2ab1054/Projects/FortStak/Todo-infra/k8s/
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3
  # docker-compose vm
    docker_compose_servers:
      hosts:
        todo-vm-docker:
          ansible_host: 192.168.122.240
          ansible_user: abdu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3
      vars:
        env: production
        app_name: todo-nodejs
        ansible_ssh_port: 22
        ansible_connection: ssh