---
- name: Deploy Todo Application on Kubernetes with ArgoCD
  hosts: k8s_servers
  become: true
  gather_facts: true

  vars:
    app_name: todo-nodejs
    docker_image: abdullatifhabiba/todo-nodejs:latest
  
  roles:
    - k8s

  