---
- name: Apply MongoDB StatefulSet
  shell: k3s kubectl apply -f /home/{{ ansible_user }}/k8s-manifests/mongodb.yml
  become: true
  register: mongodb_result

- name: Display MongoDB deployment result
  debug:
    var: mongodb_result.stdout_lines

- name: Wait for MongoDB StatefulSet to be ready
  shell: k3s kubectl wait --for=condition=ready pod -l app=mongodb -n todo-app --timeout=300s
  become: true
  register: mongodb_wait_result
  failed_when: false

- name: Check MongoDB pod status if wait failed
  shell: k3s kubectl get pods -n todo-app -l app=mongodb
  become: true
  register: mongodb_pod_status
  when: mongodb_wait_result.rc != 0

- name: Display MongoDB pod status
  debug:
    var: mongodb_pod_status.stdout_lines
  when: mongodb_wait_result.rc != 0

- name: Check MongoDB logs if pods not ready
  shell: k3s kubectl logs -l app=mongodb -n todo-app --tail=20
  become: true
  register: mongodb_logs
  when: mongodb_wait_result.rc != 0
  failed_when: false

- name: Display MongoDB logs
  debug:
    var: mongodb_logs.stdout_lines
  when: mongodb_wait_result.rc != 0 and mongodb_logs is defined

- name: Verify MongoDB service
  shell: k3s kubectl get svc mongodb -n todo-app
  become: true
  register: mongodb_service

- name: Display MongoDB service status
  debug:
    var: mongodb_service.stdout_lines