---
- name: Install required packages for k3s
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - git
    state: present
    update_cache: yes
  become: true

- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  become: true
  when: not k3s_installed.stat.exists
  register: k3s_install_result

- name: Display k3s installation result
  debug:
    var: k3s_install_result
  when: k3s_install_result.changed

- name: Set permissions for k3s config
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'
  become: true

- name: Add KUBECONFIG to .bashrc for user
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
    create: yes

- name: Set KUBECONFIG for current session
  shell: export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

- name: Wait for k3s to be ready
  shell: k3s kubectl get nodes
  register: k3s_nodes
  until: k3s_nodes.rc == 0
  retries: 15
  delay: 10
  become: true

- name: Display k3s nodes status
  debug:
    var: k3s_nodes.stdout_lines